export const PAGEPROPS_POST_REQUEST = 'PAGEPROPS_POST_REQUEST';
export const PAGEPROPS_POST_SUCCESS = 'PAGEPROPS_POST_SUCCESS';
export const PAGEPROPS_POST_FAIL = 'PAGEPROPS_POST_FAIL';

export const PAGEPROPS_PUT_REQUEST = 'PAGEPROPS_PUT_REQUEST';
export const PAGEPROPS_PUT_SUCCESS = 'PAGEPROPS_PUT_SUCCESS';
export const PAGEPROPS_PUT_FAIL = 'PAGEPROPS_PUT_FAIL';

export const PAGEPROPS_GET_REQUEST = 'PAGEPROPS_GET_REQUEST';
export const PAGEPROPS_GET_SUCCESS = 'PAGEPROPS_GET_SUCCESS';
export const PAGEPROPS_GET_FAIL = 'PAGEPROPS_GET_FAIL';